version: "3"
services:
  bareos-exporter:
    image: bareos-exporter:1.0
    ports:
      - "9118:9118"
    volumes:
      - "/opt/bareos-exporter:/app/config"
    environment:
      - CONFIG_PATH=/app/config/config.json
    container_name: bareos-exporter
