version: "3"
services:
  bareos-exporter:
    image: bareos-exporter:0.3
    ports:
      - "9118:9118"
    volumes:
      - "/Projects/Prometheus/exporters/bareos-exporter-pgsql/templates/config.json:/app/config.json"
    environment:
      - CONFIG_PATH=/app/config.json
    container_name: bareos-exporter
