version: "3"
services:
  bareos-exporter:
    image: bareos-exporter:0.6
    ports:
      - "9118:9118"
    volumes:
      - "/opt/bareos-exporter/config.json:/app/config.json"
    environment:
      - CONFIG_PATH=/app/config.json
    container_name: bareos-exporter
